#!/usr/bin/env python
from optparse import OptionParser
import libpychi, sys
parser = OptionParser(description=libpychi.data.DESCRIPTION, version=libpychi.data.VERSION)

parser.add_option("-t", '--timeout',
                  type="int",
                  default=3,
                  dest="timeout",
                  help='set the timeout of each request (has little effect)')
                  
parser.add_option('-v', '--verbose',
                  action='store_true',
                  default=False,
                  dest='verbose',
                  help='print some (hardly) interesting messages')
                  
parser.add_option('-n', '--nice',
                  action='store_true',
                  default=False,
                  dest='nice',
                  help='output nice messages, not these nasty short ones')

parser.add_option('-e', '--exit',
                    action='store_true',
                    default=False,
                    dest='exit',
                    help='return an exit code of 0, even if the internet is disconnected')
                  
parser.add_option('-s', '--short',
                     action='store_true',
                     default=False,
                     dest='short',
                     help='print short (one word) messages about the status of the connection')

(options, args) = parser.parse_args()
 
net = libpychi.Internet(timeout=options.timeout, verbose=options.verbose)
if net.connected():
    if options.nice:
        print 'We are connected to the internet!'
    elif options.short:
        print 'connected'
    else:
        print 'internet connected'
    sys.exit(0)
else:
    if options.nice:
        print 'Oh noes! No interwebs!'
    elif options.short:
        print 'disconnected'
    else:
        print 'internet disconnected'
    if options.exit:
        sys.exit(0)
    else:
        sys.exit(1)
