#!/usr/bin/env python
import gtk, gobject
import libpychi

class PychiApplet(object):
    def __init__(self):
        self.statusIcon = gtk.StatusIcon()
        self.statusIcon.connect("activate", self.onClick)
        
        self.net = libpychi.Internet()
        if self.net.connected():
            self.statusIcon.set_from_file(libpychi.data.CONNECTED_ICON)
        else:
            self.statusIcon.set_from_file(libpychi.data.DISCONNECTED_ICON)
        
    def onClick(self, event):
        print 'clicked'
        
pychiApplet = PychiApplet()
gtk.main()
