NAME = 'pychi'
DESCRIPTION = '''Check if this machine is connected to the world wide web'''
VERSION = '0.001-alpha'
ICON_DIR = '/usr/share/pixmaps/pychi/'
CONNECTED_ICON = 'internet-connected.svg'
DISCONNECTED_ICON = 'internet-disconnected.svg'
